version: "3.9"
name: magic-budget

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: magic-username
      POSTGRES_PASSWORD: magic-password
      POSTGRES_DB: magic-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
