name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Frontend Docker Image
      - name: Build and Push Frontend
        run: |
          docker build -t tom24090119/magicbudget-frontend:${{ github.sha }} -f frontend/Dockerfile ./frontend
          docker tag tom24090119/magicbudget-frontend:${{ github.sha }} tom24090119/magicbudget-frontend:latest
          docker push tom24090119/magicbudget-frontend:${{ github.sha }}
          docker push tom24090119/magicbudget-frontend:latest

      # Step 4: Build and Push Backend Docker Image
      - name: Build and Push Backend
        run: |
          docker build -t tom24090119/magicbudget-backend:${{ github.sha }} -f backend/Dockerfile ./backend
          docker tag tom24090119/magicbudget-backend:${{ github.sha }} tom24090119/magicbudget-backend:latest
          docker push tom24090119/magicbudget-backend:${{ github.sha }}
          docker push tom24090119/magicbudget-backend:latest

